version: '3.9'
services:
  portfolio:
    image: gowku/portfolio:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginx_logs:/var/log/nginx # Mount a Docker volume for the Nginx logs

volumes:
  nginx_logs:
